### PR TITLE
Display and explain locked and original input sets

### PR DESCRIPTION
**Pull request by NikolausC**
screen shot 2017-12-20 at 13 27 13

### CODE REVIEW

**Comment by NikolausC** [comment]
retest this please

**Comment by jbeast** [comment]
retest this please

**Comment by jbeast** [comment]
retest this please

**Comment by jbeast** [comment]
retest this please

**Comment by jbeast** [comment]
retest this please

**Comment by jbeast** [comment]
retest this please

**Comment by jbeast** [comment]
retest this please

**Comment by NikolausC** [comment]
retest this please

**Comment by pjvv** [comment]
retest this please

**Pull request merged**
